name: 'Testing config dependencies and optional configuration'
type: module
package: Testing
# version: VERSION

# Information added by Drupal.org packaging script on 2021-06-16
version: '9.2.0'
project: 'drupal'
datestamp: 1623847878
